LEFT:
  arm_id: "fr3"
  arm_prefix: "left"
  fake_sensor_commands: "false"
  joint_sources: ["joint_states", "franka_gripper/joint_states"]
  joint_state_rate: 30 
  load_gripper: "true"
  namespace: "left"
  robot_ip: "172.16.0.2"
  urdf_file: "fr3/fr3.urdf.xacro"
  use_fake_hardware: "false"
  use_rviz: "false"
  # mounting roll, pitch, yaw in rad
  arm_mounting_orientation: [0.8933480924,-0.1745607426,0.4633450616]

RIGHT:
  arm_id: "fr3"
  arm_prefix: "right"
  fake_sensor_commands: "false"
  joint_sources: ["joint_states", "franka_gripper/joint_states"]
  joint_state_rate: 30
  load_gripper: "true"
  namespace: "right"
  robot_ip: "172.16.1.2"
  urdf_file: "fr3/fr3.urdf.xacro"
  use_fake_hardware: "false"
  use_rviz: "false"
  # mounting roll, pitch, yaw in rad
  arm_mounting_orientation: [-0.8933480924,-0.1745607426,-0.4633450616]